spring.application.name=SpringDataJpaDemo
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=njsdhsdhbvsbv3e42322b23bh2bhb2b4h2b4h23hj2j3jb4
